controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

abonnement_show:
    path: /abonnement/{id}
    controller: App\Controller\AbonnementController::show
    requirements:
        id: '\d+'
